DoAnChuyenNganh/DoAnChuyenNganh-master/doan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('academy/', TemplateView.as_view(template_name='academy-profile.html')),
                  path('tutor-list', TemplateView.as_view(template_name='tutor-list.html'), name='tutor-list'),
                  path('course-list', TemplateView.as_view(template_name='course-list.html'), name='course-list'),
                  path('academy-list', TemplateView.as_view(template_name='academy-list.html'), name='academy-list'),

                  path('course-best-review', TemplateView.as_view(template_name='course-best-review.html')),
                  path('course-most-watch', TemplateView.as_view(template_name='course-most-watch.html')),
                  path('course-best-price', TemplateView.as_view(template_name='course-best-price.html')),

                  path('tutor-best-review', TemplateView.as_view(template_name='tutor-best-review.html')),
                  path('tutor-most-watch', TemplateView.as_view(template_name='tutor-most-watch.html')),
                  path('tutor-best-price', TemplateView.as_view(template_name='tutor-best-price.html')),

                  path('academy-best-review', TemplateView.as_view(template_name='academy-best-review.html')),
                  path('academy-most-watch', TemplateView.as_view(template_name='academy-most-watch.html')),
                  path('academy-best-price', TemplateView.as_view(template_name='academy-best-price.html')),

                  path('base', TemplateView.as_view(template_name='base.html')),
                  path('homepage', TemplateView.as_view(template_name='homepage.html')),
                  path('term-of-uses', TemplateView.as_view(template_name='term-of-uses.html')),

                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('', include('accounts.urls')),
                  path('user_profile/', include('polls.urls'), name='show_user_profile'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DoAnChuyenNganh/DoAnChuyenNganh-master/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    level = (
        ('G', 'Vàng'),
        ('S', 'Bạc'),
        ('D', 'Mặc định'),
    )
    account_level = models.CharField(max_length=1, choices=level,
                                     default='D')

    type = (
        ('A', 'Trung tâm'),
        ('S', 'Học sinh'),
        ('T', 'Gia sư'),
    )
    account_type = models.CharField(max_length=1, choices=type,
                                    default='S')

    is_agreed = models.BooleanField()

    def __str__(self):
        return self.user.username

DoAnChuyenNganh/DoAnChuyenNganh-master/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile


class ExtendedUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    last_name = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'email', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=True)

        user.email = self.cleaned_data['email']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('account_type', 'is_agreed')

DoAnChuyenNganh/DoAnChuyenNganh-master/templates/base.html
{% load staticfiles %}
<head>
    {% block title %}

    {% endblock %}
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block styles %}

    {% endblock %}

</head>
<body style="background-color: #f2f2f2">

<header>
    <!-- BEGIN OF Navigation Bar -->
    <nav class="navbar navbar-expand-sm bg-original navbar-dark fixed-top">
        <!-- Web Logo -->
        <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.png'%}"></a>
        <div class="search-bar">
            <form>
                <input type="text" name="search" placeholder="Nhập bất cứ thứ gì bạn muốn tìm...">
                <button type="submit"><i class="fas fa-search"></i></button>
            </form>
        </div><!--search-bar end-->

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navigation Items -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'course-list' %}"><i class="fas fa-certificate"></i> Khóa Học</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tutor-list' %}"><i class="fas fa-user-tie"></i> Gia Sư</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'academy-list' %}"><i class="fas fa-building"></i> Trung Tâm</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Chào {{ user.last_name }}!
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        {% for item in user_type %}
                        {% if item.account_type == 'T' %}
                        <a class="dropdown-item" href="{% url 'show_user_profile' user.username %}">Hồ sơ của tôi</a>
                        {% elif item.account_type == 'A' %}
                        <a class="dropdown-item" href="{% url 'show_user_profile' user.username %}">Hồ sơ trung tâm</a>
                        {% else %}
                        <a class="dropdown-item">Hồ sơ học sinh</a>
                        {% endif %}
                        {% endfor %}
                        <a class="dropdown-item" href="{% url 'logout' %}">Đăng xuất</a>
                    </div>
                </li>
                {% else %}
                <a class="btn btn-outline-light btn-sm" href="{% url 'login' %}">Đăng Nhập
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- END OF Navigation Bar -->
</header>
{% block content %}

{% endblock %}
<!-- BEGIN OF FOOTER -->
<footer>
    <div style="background-color: #fff;">
        <section class="container pt-3 text-center">
            <div class="row">
                <div class="col-lg-12">
                    <p>Cộng đồng hơn 15,000 thành viên đang chờ bạn</p>
                </div>
            </div>
        </section>

        <!-- Icon -->
        <div class="container-fluid">
            <div class="row justify-content-center text-center">
                <a class="social-btn" href=""><img src="{% static 'images/facebook.png'%}"></a>
                <a class="social-btn" href=""><img src="{% static 'images/twitter.png'%}"></a>
                <a class="social-btn" href=""><img src="{% static 'images/google-plus.png'%}"></a>
                <a class="social-btn" href=""><img src="{% static 'images/youtube.png'%}"></a>
                <a class="social-btn" href=""><img src="{% static 'images/zalo.png'%}"></a>
            </div>
        </div>
        <!-- END OF Social Network -->
    </div>

    <div class="footer-main-category">
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-sm-6 col-xs-6">
                    <div class="list-links">
                        <h3>Bạn đang muốn</h3>
                        <ul>
                            <li><a href="/tao-lop-hoc">Đăng yêu cầu tìm gia sư</a></li>
                            <li><a href="/teacher">Xem danh sách gia sư</a></li>
                            <li><a href="https://www.giasuvip.vn" target="_blank">Dịch vụ gia sư VIP</a></li>
                            <li><a href="/become-agency">Mở trung tâm GS<span style="color:yellow"> (hot)</span></a>
                            </li>
                            <li><a href="#recommendation" class="popup-modal">Góp ý cho chúng tôi</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-2 col-sm-6 col-xs-6">
                    <div class="list-links">
                        <h3>Danh mục gia sư</h3>
                        <ul>
                            <li><a href="/gia-su-toan">Gia sư toán</a></li>
                            <li><a href="/gia-su-tieng-anh">Gia sư Tiếng Anh</a></li>
                            <li><a href="/gia-su-online">Gia sư Online</a></li>
                            <li><a href="/gia-su-ngoai-ngu">Gia sư ngoại ngữ</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-2 col-sm-6 col-xs-6">
                    <div class="list-links">
                        <h3>Chúng tôi</h3>
                        <ul>
                            <li><a href="/gioi-thieu">Về chúng tôi</a></li>
                            <li><a href="/jobs">Tuyển dụng</a></li>
                            <li><a href="/terms-of-use" rel="nofollow">Quy định MXH Chúng tôi</a></li>
                            <li><a href="/quy-dinh-su-dung-san-giao-dich-tmdt" rel="nofollow">Quy định sàn TMĐT</a></li>
                            <li><a href="/privacy-policy" rel="nofollow">CC bảo mật thông tin</a></li>
                            <li><a href="/contact">Liên hệ</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-2 col-sm-6 col-xs-6">
                    <div class="list-links">
                        <h3>Hỗ Trợ</h3>
                        <ul>
                            <li><a href="/support">Hướng dẫn sử dụng</a></li>
                            <li><a href="/affiliate-program">Affiliate Program</a></li>
                            <li><a href="/invite-friend">Mời bạn bè</a></li>
                            <li><a href="/khieu-nai">Khiếu nại</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-2 col-sm-6 col-xs-6">
                    <div class="list-links">
                        <h3>Dự án cộng đồng</h3>
                        <ul>
                            <li><a href="/cam-nang-tri-thuc">Cẩm nang tri thức</a></li>
                            <li><a href="/kien-thuc-du-hoc">Kiến thức du học</a></li>
                            <li><a href="/project-education-support">Gia sư miễn phí</a></li>
                            <li><a href="/books-in-the-city">Sách truyền tay</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-2 col-sm-6 col-xs-6">
                    <div class="list-links">
                        <h3>Dành Cho Gia sư</h3>
                        <ul>
                            <li><a href="/dang-ky-gia-su">Trở thành gia sư</a></li>
                            <li><a href="/class">Danh sách lớp mới</a></li>
                            <li><a href="/become-teacher">Hướng dẫn nhận lớp</a></li>
                            <li><a href="/chinh-sach-phi" rel="nofollow">Chính sách phí</a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</footer><!--footer end-->
<!-- END OF FOOTER -->

{% block scripts %}

{% endblock %}


</body>

DoAnChuyenNganh/DoAnChuyenNganh-master/templates/signup.html
<!-- templates/signup.html -->
{% load staticfiles %}
{% block title %}<title>Đăng Ký</title>{% endblock %}

{% block styles %}
<!-- Bootstrap CDN -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<!-- Font Awesome CDN -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
      integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<!-- CSS for Log Page -->
<link rel="stylesheet" href="{% static 'css/customized-bootstrap.css'%}">
<link rel="stylesheet" href="{% static 'css/login-signup.css'%}">
<link rel="stylesheet" href="{% static 'css/log-page.css'%}">
{% endblock %}

<form method="POST">
    {% csrf_token %}
    <div class="container justify-content-center">
        <div class="back-button">
            <a href="{% url 'login' %}">
                <i class="fas fa-arrow-left fa-2x"></i>
            </a>
        </div>
        <h1>Đăng Ký</h1>
        <div class="text-center customSelectOption">
            <select name="account_type" id="id_account_type">
                <option value="A">Trung tâm</option>
                <option value="S" selected="">Học sinh</option>
                <option value="T">Gia sư</option>
            </select>
        </div>
        <div class="user-input icon-input">
            <div class="form-group">
                <input type="text" name="last_name" required="" id="id_last_nme"
                       placeholder="Họ tên của bạn...">
                <i class="fas fa-user-plus fa-lg fa-fw"></i>
            </div>
        </div>
        <div class="user-input icon-input">
            <div class="form-group">
                <input type="text" name="username" autofocus="" required="" id="id_username"
                       placeholder="Tên tài khoản...">
                <i class="fas fa-user fa-lg fa-fw"></i>
            </div>
        </div>
        <div class="user-input icon-input">
            <div class="form-group">
                <input type="email" name="email" required="" id="id_email"
                       placeholder="Email...">
                <i class="fas fa-envelope fa-lg fa-fw"></i>
            </div>
        </div>
        <div class="user-input icon-input">
            <div class="form-group">
                <input type="password" name="password1" required="" id="id_password1"
                       placeholder="Mật khẩu...">
                <i class="fas fa-lock fa-lg fa-fw"></i>
            </div>
        </div>
        <div class="user-input icon-input">
            <div class="form-group">
                <input type="password" name="password2" required="" id="id_password2"
                       placeholder="Nhập lại mật khẩu...">
                <i class="fas fa-lock fa-lg fa-fw"></i>
            </div>
        </div>
        <div class="customCheckbox">
            <input type="checkbox" name="is_agreed" id="id_is_agreed">
            <label for="id_is_agreed" style="font-size: 12px;">Tôi đồng ý với <a href="term-of-uses" target="_blank">Điều
                khoản sử dụng</a></label>
        </div>
        <div style="padding-bottom: 10px;">
            <button type="submit" id="btn-submit" name="submit" class="btn btn-primary btn-submit font-weight-bold">Đăng
                Ký
            </button>
        </div>
        <hr>
        <div class="text-center" style="padding-bottom: 10px; font-size: 12px;">
            <h5 style="color: grey; font-size: 14px; font-weight: bold;">HAY</h5>
            Bạn đã có tài khoản? <a href="{% url 'login' %}">Đăng Nhập</a>
        </div>

    </div>
</form>

{% block scripts %}
<!-- JAVASCRIPT -->
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/jquery.min.js'%}"></script>
<script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
{% endblock %}